### PR TITLE
Add "Meta Quest compatible" flag

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**
Fixes https://github.com/pwa-builder/PWABuilder/issues/3154.

See also https://github.com/pwa-builder/PWABuilder/pull/3162.

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
@jgw96 @JudahGabriel This pull request is ready to review and merge. :wink:

**Comment by amrutha95** [comment]
Hey @FluorescentHallucinogen , thank you so much for this PR! We are just waiting on talking to Meta who we've been partnering with to create the current Meta Quest packaging service. Will keep you updated.

**Review by amrutha95 — APPROVED** [review]

**Comment by amrutha95** [comment]
@khmyznikov or I will get this tested and merged ASAP.

**Comment by khmyznikov** [comment]
> @khmyznikov or I will get this tested and merged ASAP.

Works for me

**Pull request merged**
